-
  name: 'Neos :: Frontend :: Podcast episdoe with feed.xml'
  uriPattern: '{node}.{audiotype}.podcast.xml'
  defaults:
    '@package': Neos.Neos
    '@controller': Frontend\Node
    '@action': show
    '@format': podcast.xml
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface
  appendExceedingArguments: true
