
Neos:
  Flow:
    mvc:
      routes:
        DasPerfekteTeam.Podcaster:
          position: 'start'
  Neos:
    fusion:
      autoInclude:
        DasPerfekteTeam.Podcaster: true
  Fusion:
    defaultContext:
      Podcaster: DasPerfekteTeam\Podcaster\Fusion\Helpers\FeedHelper
